site_name: Join Monster
site_description: A GraphQL-to-SQL execution layer.
repo_url: https://github.com/stems/join-monster
site_favicon: img/join_monster.ico
theme: readthedocs
extra_javascript:
  # MkDocs includes an old version of highlight.js, but it doesn't recognize all modern JS syntax, import a newer version
  - //cdnjs.cloudflare.com/ajax/libs/highlight.js/8.4/highlight.min.js
  - custom.js
extra_css: 
  - custom.css
pages:
  - Introduction: index.md
  - "The Problem We Solve": problem.md
  - "How It Works": how-it-works.md
  - "Usage":
    - "1. Declare Data Model": data-model.md
    - "2. Map Objects to Tables": map-to-table.md
    - "3. Add Metadata to Fields": field-metadata.md
    - "4. Calling Join Monster": call-function.md
    - "5. Joining Objects": start-joins.md
    - "6. Arbitrary Depth": arbitrary-depth.md
    - "7. Many-to-Many Joins": many-to-many.md
    - "8. Where Conditions": where.md
    - "9. Relay Support": relay.md
  - "Pros and Cons": pros-cons.md
  - Warnings: warnings.md
  - API: API.md
  - "Internal Workings": internals.md
  - "Change Log": CHANGELOG.md
